### PR TITLE
docs: minor updates for clarity

### PR DESCRIPTION
**Pull request by johnsonstephan**
**Purpose of this Pull Request**

I've made a few minor edits to improve the clarity of the documentation. 

**Additional Context**

I've ensured that the formatting and structure of these entries are consistent with the other items in the document.

If any further changes or adjustments are needed, please let me know, and I'll be happy to make them.

### CODE REVIEW

**Comment by johnsonstephan** [comment]
Hi @PatrickAlphaC, I've submitted a PR with minor updates to the written version of the "what is an audit" from section 2 -- 2 (2-audit/1-what-is-an-audit).

Would you be the best person to review this?

**Comment by johnsonstephan** [comment]
Hi @solhosty, @ShivamDeshmukh21, @Equious - I noticed that you all have been maintaining the repo and perhaps are better positioned than @PatrickAlphaC to review this PR? 

Please let me know if you may have any questions. Thanks.

**Comment by PatrickAlphaC** [comment]
Thanks for this! Sorry on our delay. I'll bring this up!

**Comment by solhosty** [comment]
hey @johnsonstephan! I'll be looking at this today and doing a sync with a few other PRs here!

**Comment by johnsonstephan** [comment]
@PatrickAlphaC - No problem, I'm sure things are busy with the start of the year! 
@solhosty - Thank you! And I'll be sure to tag you next time 🙏🏾

**Pull request merged**
