### PR TITLE
style: :speech_balloon: typo and grammar fixes

### PR DESCRIPTION
**Pull request by Beefy-py**

### CODE REVIEW

**Comment by EngrPips** [comment]
Hello @Beefy-py, Thanks for the contribution and this will be addressed appropriately as soon as possible.

**Review by cromewar — CHANGES_REQUESTED** [review]
Hey there, thanks for summiting the changes.

We need to respect the correct format though, can you please turn off your auto formatter before sending the PR? 

We need to keep the `-` instead the `+` on your commit.

**Comment by Beefy-py** [comment]
@cromewar 
I'm not sure I understood you fully. Which format is used? I am using the Prettier VScode plug-in.
Can you clarify which lines? Maybe by adding comments

**Comment by cromewar** [comment]
Sure @Beefy-py you are replacing all the `-` for `+` here:

image

can you please keep the format the same?

**Comment by Beefy-py** [comment]
@cromewar 
Honestly, I'm still confused as to what you mean 😅 
Because I didn't encounter minus symbols when I cloned the repo to my local machine.
GitHub automatically puts those to mark where deletions and insertions have been made.

**Review by cromewar — APPROVED** [review]

**Pull request merged**
