### PR TITLE
Solidity S1-S3

### PR DESCRIPTION
**Pull request by sunnyStefi**
content, design, tests

### CODE REVIEW

**Comment by sunnyStefi** [comment]
@solhosty this is the PR that contains all the Solidity changes S1-S3 rebased on the updated dev

**Comment by solhosty** [comment]
Hey @sunnyStefi, sorry I was OOO yesterday. Looks like they did 1 more restructure here due to a re-order. Are you able to add the blank lesson in and re-order and that should resolve conflicts? 

If it's any easier to open a new PR, let me know. We can get this in today if you have time to resolve this. 

I appreciate your patience!

**Comment by solhosty** [comment]
> Hey @sunnyStefi, sorry I was OOO yesterday. Looks like they did 1 more restructure here due to an addition for a plugin fix for ZK. Are you able to resolve one more time and I will make sure this PR get's priority when resolved to go into production.
> 
> If it's any easier to open a new PR, let me know. We can get this in today if you have time to resolve this.
> 
> I appreciate your patience!

I may be able to resolve these towards EOD if you don't get to it. Adding a task on my end to check on this before clocking off, then I can resolve if anything.

**Comment by sunnyStefi** [comment]
@solhosty should be ok now!

**Review by solhosty — APPROVED** [review]
This looks good! Moving to dev right now!

**Pull request merged**
