### PR TITLE
Update +page.md

### PR DESCRIPTION
**Pull request by TheWilsonGlobal**

### CODE REVIEW

**Comment by EngrPips** [comment]
Hello @TheWilsonGlobal, Thanks for this contribution, and this will be attended to appropriately as soon as possible

**Comment by TheWilsonGlobal** [comment]
This PR was commit to fix issue #167

**Comment by solhosty** [comment]
Hi @TheWilsonGlobal , please make sure any contributions in the future go into our `dev` branch. If you could also resolve the above conflicts that would be great!

**Comment by cromewar** [comment]
Yes please, contributions must be made on dev branch, also please be sure your commits are clear and don't include things like: 

- "sfdfadf"
- Test

I will close this PR, but I encourage you to send it over again using the PR guidelines.

**Comment by TheWilsonGlobal** [comment]
Many thanks @solhosty  and @cromewar 
I already create PR #184 followed by your advice

**Pull request closed without merging**
