### PR TITLE
AA written lessons 3-5 plus image fix for lessons 1-2

### PR DESCRIPTION
**Pull request by SupaMega24**
**Description**

- Created a written lesson **3  - 5** for the new Account Abstraction section of the Advanced Foundry course.
- Created a new folder for images in the static directory to match this section and lesson
- Fixed issues with images from lesson 1 and 2 (weren't rendering in course) 
- I used appropriate links and images to mirror the video lesson.
- I stayed true to what is covered in the video and didn't go too far into detail as it will be covered in future lessons.
- I added some review questions at the end of lesson 3.

I look forward to your review and feedback.

### CODE REVIEW

**Comment by SupaMega24** [comment]
NOTE: For lesson 1 and 2, I didn't change any other code except for img.

**Comment by solhosty** [comment]
Hey @SupaMega24 ! Same thing here, great work! Are we just able to resolve conflicts and ping when this is set?

Thank you!

**Comment by SupaMega24** [comment]
Thank you. I suppose I just need to do a git fetch. I'll try it out as soon as I get a chance.

**Comment by SupaMega24** [comment]
@solhosty Conflicts resolved 👍

**Comment by solhosty** [comment]
Awesome thanks @SupaMega24 , we'll get this into dev first and prod shortly!

**Pull request merged**
